apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
   name: dnsservices.io.bb.com.br
spec:
   group: io.bb.com.br
   version: v1alpha1
   scope: Namespaced
   names:
      plural: dnsservices
      singular: dnsservice
      kind: DnsService
   validation:
      openAPIV3Schema:
         required:2
         - spec
         properties:
            spec:
               required:
               - authkey
               - server
               - zone
               - hostname
               - type
               - ttl
               - records
               - description
               properties:
                  authkey:
                     type: string
                     minimum: 1
                  server:
                     type: string
                     minimum: 1
                  zone:
                     type: string
                     minimum: 1
                  hostname:
                     type: string
                     minimum: 1
                  type:
                     type: string
                     minimum: 1
                  domain:
                     type: string
                     minimum: 1
                  ttl:
                     type: string
                     minimum: 1
                  records:
                     type: string
                     minimum: 1
                  description:
                     type: string
                     minimum: 1