/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "dnsservice-controller/pkg/apis/dnsservice/v1"
	scheme "dnsservice-controller/pkg/client/clientset/versioned/scheme"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DnsServicesGetter has a method to return a DnsServiceInterface.
// A group's client should implement this interface.
type DnsServicesGetter interface {
	DnsServices(namespace string) DnsServiceInterface
}

// DnsServiceInterface has methods to work with DnsService resources.
type DnsServiceInterface interface {
	Create(*v1.DnsService) (*v1.DnsService, error)
	Update(*v1.DnsService) (*v1.DnsService, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.DnsService, error)
	List(opts meta_v1.ListOptions) (*v1.DnsServiceList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DnsService, err error)
	DnsServiceExpansion
}

// myResources implements DnsServiceInterface
type myResources struct {
	client rest.Interface
	ns     string
}

// newDnsServices returns a DnsServices
func newDnsServices(c *TrstringerV1Client, namespace string) *myResources {
	return &myResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myResource, and returns the corresponding myResource object, and an error if there is any.
func (c *myResources) Get(name string, options meta_v1.GetOptions) (result *v1.DnsService, err error) {
	result = &v1.DnsService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DnsServices that match those selectors.
func (c *myResources) List(opts meta_v1.ListOptions) (result *v1.DnsServiceList, err error) {
	result = &v1.DnsServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dnsservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested myResources.
func (c *myResources) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dnsservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch(context.TODO())
}

// Create takes the representation of a myResource and creates it.  Returns the server's representation of the myResource, and an error, if there is any.
func (c *myResources) Create(myResource *v1.DnsService) (result *v1.DnsService, err error) {
	result = &v1.DnsService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dnsservices").
		Body(myResource).
		Do(context.TODO()).
		Into(result)
	return
}

// Update takes the representation of a myResource and updates it. Returns the server's representation of the myResource, and an error, if there is any.
func (c *myResources) Update(myResource *v1.DnsService) (result *v1.DnsService, err error) {
	result = &v1.DnsService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dnsservices").
		Name(myResource.Name).
		Body(myResource).
		Do(context.TODO()).
		Into(result)
	return
}

// Delete takes name of the myResource and deletes it. Returns an error if one occurs.
func (c *myResources) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsservices").
		Name(name).
		Body(options).
		Do(context.TODO()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *myResources) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dnsservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do(context.TODO()).
		Error()
}

// Patch applies the patch and returns the patched myResource.
func (c *myResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.DnsService, err error) {
	result = &v1.DnsService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dnsservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.TODO()).
		Into(result)
	return
}
