/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	dnsservice_v1 "dnsservice-controller/pkg/apis/dnsservice/v1"
	versioned "dnsservice-controller/pkg/client/clientset/versioned"
	internalinterfaces "dnsservice-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "dnsservice-controller/pkg/client/listers/dnsservice/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DnsServiceInformer provides access to a shared informer and lister for
// DnsServices.
type DnsServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DnsServiceLister
}

type myResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDnsServiceInformer constructs a new informer for DnsService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDnsServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDnsServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDnsServiceInformer constructs a new informer for DnsService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDnsServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrstringerV1().DnsServices(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TrstringerV1().DnsServices(namespace).Watch(options)
			},
		},
		&dnsservice_v1.DnsService{},
		resyncPeriod,
		indexers,
	)
}

func (f *myResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDnsServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dnsservice_v1.DnsService{}, f.defaultInformer)
}

func (f *myResourceInformer) Lister() v1.DnsServiceLister {
	return v1.NewDnsServiceLister(f.Informer().GetIndexer())
}
